language: node_ks
node_js:
  - "node"
notifications:
  email:
    recipients:
    - simon.humbert@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: $API_KEY
  app: shumbert95/api_pokemon
  on:
    repo: shumbert95/api_pokemon